[metadata]
name = "Swamp Dweller"
origin_url = "https://github.com/yonatan-perel/lake-dweller.nvim"

[colors]
foreground = "#e0e8d8"
background = "#101510"

cursor_bg = "#e0e8d8"
cursor_fg = "#101510"
cursor_border = "#e0e8d8"

selection_bg = "#304030"
selection_fg = "#e0e8d8"

scrollbar_thumb = "#708068"
split = "#708068"

ansi = [
  "#101510",  # 0 black
  "#f08080",  # 1 red
  "#90c890",  # 2 green
  "#d8c070",  # 3 yellow
  "#e0d080",  # 4 blue (using func color)
  "#e8a070",  # 5 magenta (using string color)
  "#60c090",  # 6 cyan
  "#e0e8d8",  # 7 white
]

brights = [
  "#708068",  # 8 bright black
  "#f08080",  # 9 bright red
  "#90c890",  # 10 bright green
  "#d8c070",  # 11 bright yellow
  "#e0d080",  # 12 bright blue
  "#e8a070",  # 13 bright magenta
  "#80c080",  # 14 bright cyan
  "#e0e8d8",  # 15 bright white
]

[colors.tab_bar]
background = "#1a241a"

[colors.tab_bar.active_tab]
bg_color = "#1a281a"
fg_color = "#e0e8d8"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#1a241a"
fg_color = "#708068"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1a241a"
fg_color = "#e0e8d8"
italic = true

[colors.tab_bar.new_tab]
bg_color = "#1a241a"
fg_color = "#708068"

[colors.tab_bar.new_tab_hover]
bg_color = "#1a241a"
fg_color = "#e0e8d8"
italic = true
