return function(t, config)
    local italic = config.italics or false
    return {
        -- Git commit
        gitcommitSummary = { fg = t.fg, bold = true },
        gitcommitOverflow = { fg = t.error, bold = true },
        gitcommitHeader = { fg = t.keyword, bold = true },
        gitcommitOnBranch = { fg = t.keyword },
        gitcommitBranch = { fg = t.type, bold = true },
        gitcommitUnmerged = { fg = t.error, bold = true },
        gitcommitUntracked = { fg = t.keyword },
        gitcommitDiscarded = { fg = t.error },
        gitcommitSelected = { fg = t.func },
        gitcommitDiscardedType = { fg = t.error },
        gitcommitSelectedType = { fg = t.func },
        gitcommitDiscardedFile = { fg = t.error },
        gitcommitSelectedFile = { fg = t.func },
        gitcommitFile = { fg = t.fg },
        gitcommitTrailerToken = { fg = t.keyword, bold = true },
        gitcommitTrailerValue = { fg = t.string },

        -- Oil.nvim
        OilFile = { fg = t.fg },
        OilSymlink = { fg = t.func, italic = italic },
        OilHidden = { fg = t.keyword, italic = italic },
        OilHeader = { fg = t.keyword, bold = true },
        OilBorder = { fg = t.keyword },
        OilWinBar = { fg = t.keyword },
        OilIndent = { fg = t.keyword },
        OilExpander = { fg = t.keyword },
        OilColumns = { fg = t.keyword },
        OilModified = { fg = t.error, bold = true },
        OilDeleted = { fg = t.deleted },
        OilAdded = { fg = t.added },
        OilWarning = { fg = t.warn },
        OilError = { fg = t.error },
        OilSelected = { fg = t.fg, underline = true },
        OilCursorLine = { fg = t.fg, underline = true },

        -- nvim-cmp
        CmpItemAbbr = { fg = t.fg },
        CmpItemAbbrDeprecated = { fg = t.keyword, strikethrough = true },
        CmpItemAbbrMatch = { fg = t.keyword, bold = true },
        CmpItemAbbrMatchFuzzy = { fg = t.keyword },
        CmpItemMenu = { fg = t.keyword, italic = italic },
        CmpItemKind = { fg = t.fg },
        CmpItemKindFunction = { fg = t.func },
        CmpItemKindMethod = { fg = t.func },
        CmpItemKindConstructor = { fg = t.func },
        CmpItemKindClass = { fg = t.type },
        CmpItemKindStruct = { fg = t.type },
        CmpItemKindInterface = { fg = t.type },
        CmpItemKindTypeParameter = { fg = t.type },
        CmpItemKindModule = { fg = t.type },
        CmpItemKindNamespace = { fg = t.type },
        CmpItemKindVariable = { fg = t.fg },
        CmpItemKindProperty = { fg = t.fg },
        CmpItemKindField = { fg = t.fg },
        CmpItemKindConstant = { fg = t.constant },
        CmpItemKindEnum = { fg = t.constant },
        CmpItemKindEnumMember = { fg = t.constant },
        CmpItemKindKeyword = { fg = t.keyword },
        CmpItemKindText = { fg = t.string },
        CmpItemKindString = { fg = t.string },
        CmpItemKindColor = { fg = t.string },
        CmpItemKindSnippet = { fg = t.comment },
        CmpItemKindFile = { fg = t.fg },
        CmpItemKindFolder = { fg = t.fg },
        CmpItemKindReference = { fg = t.fg },
        CmpItemKindUnit = { fg = t.fg },
        CmpItemKindValue = { fg = t.fg },

        -- Trouble.nvim
        TroubleNormal = { fg = t.fg, bg = t.bg },
        TroubleNormalNC = { fg = t.fg_dim, bg = t.bg },
        TroubleIndent = { fg = t.fg, bg = t.bg },
        TroubleCount = { fg = t.fg, bg = t.selection },
        TroubleDiagnosticsItemSource = { fg = t.keyword, bg = t.bg, italic = italic },
        TroubleCode = { fg = t.fg_dim, bg = t.bg },
        TroubleIconDirectory = { fg = t.fg_dim, bg = t.bg },
        TroubleIconEvent = { fg = t.fg_dim, bg = t.bg },

        -- Telescope.nvim
        TelescopeTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopeResultsTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopeMultiSelection = { fg = t.func, bg = t.selection },
        TelescopeSelectionCaret = { fg = t.keyword, bg = t.selection },
        TelescopeMatching = { fg = t.keyword, bg = t.bg, bold = true },
        TelescopePromptTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopePromptPrefix = { fg = t.keyword, bg = t.bg },
        TelescopePromptCounter = { fg = t.keyword, bg = t.bg },
        TelescopePreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopePreviewMatch = { fg = t.keyword, bg = t.bg, underline = true },

        -- fzf-lua
        FzfLuaTitle = { fg = t.fg, bg = t.bg, bold = true },
        FzfLuaPrompt = { fg = t.keyword, bg = t.bg },
        FzfLuaInfo = { fg = t.keyword, bg = t.bg, italic = italic },
        FzfLuaPath = { fg = t.type, bg = t.bg },
        FzfLuaHeaderBind = { fg = t.keyword, bg = t.bg },
        FzfLuaHeaderText = { fg = t.keyword, bg = t.bg },
        FzfLuaCursor = { fg = t.fg_inverse, bg = t.fg },
        FzfLuaCursorLine = { fg = t.fg, bg = t.selection },
        FzfLuaCursorLineNr = { fg = t.fg_dim, bg = t.selection },
        FzfLuaMatch = { fg = t.keyword, bg = t.bg, bold = true },
        FzfLuaSearch = { fg = t.fg, bg = t.selection },
        FzfLuaMarker = { fg = t.func, bg = t.bg, bold = true },
        FzfLuaPreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        FzfLuaPreviewLine = { fg = t.fg, bg = t.selection },
        FzfLuaPreviewSearch = { fg = t.fg, bg = t.selection },
        FzfLuaPreviewMatch = { fg = t.keyword, bg = t.bg, underline = true },

        -- which-key.nvim
        WhichKeyGroup = { fg = t.type, bg = t.bg, bold = true },
        WhichKeySeparator = { fg = t.fg_dim, bg = t.bg },
        WhichKeyFloat = { fg = t.fg, bg = t.bg },
        WhichKeyValue = { fg = t.keyword, bg = t.bg },
        WhichKeyNormal = { fg = t.fg, bg = t.bg },
        WhichKeyTitle = { fg = t.fg, bg = t.bg, bold = true },

        -- nvim-notify
        NotifyBackground = { bg = t.fg_inverse },

        -- Snacks.nvim
        SnacksPickerNormal = { fg = t.fg, bg = t.bg },
        SnacksPickerBorder = { fg = t.fg, bg = t.bg },
        SnacksPickerTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerInput = { fg = t.fg, bg = t.bg },
        SnacksPickerInputBorder = { fg = t.fg, bg = t.bg },
        SnacksPickerInputTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerList = { fg = t.fg, bg = t.bg },
        SnacksPickerListBorder = { fg = t.fg, bg = t.bg },
        SnacksPickerListTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerListCursorLine = { fg = t.fg, bg = t.selection },
        SnacksPickerPreview = { fg = t.fg, bg = t.bg },
        SnacksPickerPreviewBorder = { fg = t.fg, bg = t.bg },
        SnacksPickerPreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerPreviewLine = { fg = t.fg, bg = t.selection },
        SnacksPickerMatch = { fg = t.keyword, bg = t.bg, bold = true },
        SnacksPickerDir = { fg = t.type, bg = t.bg },
        SnacksPickerFile = { fg = t.fg, bg = t.bg },
        SnacksPickerSelected = { fg = t.func, bg = t.selection },
        SnacksPickerIdx = { fg = t.fg_dim, bg = t.bg },
        SnacksPickerRow = { fg = t.fg_dim, bg = t.bg },
        SnacksPickerLabel = { fg = t.warn, bg = t.bg, bold = true },

        -- gitsigns.nvim
        GitSignsUntracked = { fg = t.fg_dim },
        GitSignsUntrackedNr = { fg = t.fg_dim },
        GitSignsAddLn = { bg = t.selection },
        GitSignsChangeLn = { bg = t.selection },
        GitSignsChangedeleteLn = { bg = t.selection },
        GitSignsUntrackedLn = { bg = t.selection },
        GitSignsUntrackedCul = { fg = t.fg_dim },
        GitSignsAddPreview = { fg = t.added, bg = t.float_bg },
        GitSignsDeletePreview = { fg = t.deleted, bg = t.float_bg },
        GitSignsCurrentLineBlame = { fg = t.virtual_text, italic = italic },
        GitSignsAddInline = { bg = t.selection_added },
        GitSignsDeleteInline = { bg = t.selection_deleted },
        GitSignsChangeInline = { bg = t.selection },
        GitSignsDeleteVirtLnInLine = { fg = t.deleted, bg = t.selection_deleted },
        GitSignsVirtLnum = { fg = t.fg_dim },

        -- Noice.nvim
        NoiceCmdline = { fg = t.fg, bg = t.bg },
        NoiceCmdlineIcon = { fg = t.keyword },
        NoiceCmdlinePopupTitle = { fg = t.fg, bg = t.bg, bold = true },
        NoiceCursor = { fg = t.fg_inverse, bg = t.fg },
        NoiceFormatConfirm = { fg = t.keyword },
        NoiceFormatConfirmDefault = { fg = t.func, bold = true },
        NoiceFormatDate = { fg = t.keyword, italic = italic },
        NoiceFormatEvent = { fg = t.keyword, italic = italic },
        NoiceFormatKind = { fg = t.keyword },
        NoiceFormatLevelDebug = { fg = t.keyword },
        NoiceFormatLevelOff = { fg = t.keyword },
        NoiceFormatLevelTrace = { fg = t.keyword },
        NoiceFormatProgressDone = { fg = t.func, bold = true },
        NoiceFormatProgressTodo = { fg = t.keyword },
        NoiceFormatTitle = { fg = t.fg, bold = true },
        NoiceLspProgressClient = { fg = t.type, bold = true },
        NoiceLspProgressSpinner = { fg = t.keyword },
        NoiceLspProgressTitle = { fg = t.fg },
        NoiceMini = { fg = t.fg, bg = t.bg },
        NoicePopup = { fg = t.fg, bg = t.bg },
        NoicePopupmenu = { fg = t.fg, bg = t.bg },
        NoicePopupmenuMatch = { fg = t.keyword, bold = true },
        NoiceScrollbar = { fg = t.keyword, bg = t.bg },
        NoiceScrollbarThumb = { bg = t.selection },
        NoiceSplit = { fg = t.fg, bg = t.bg },
        NoiceVirtualText = { fg = t.virtual_text, italic = italic },

        -- blink.cmp
        BlinkCmpMenu = { fg = t.fg, bg = t.bg },
        BlinkCmpMenuBorder = { fg = t.fg, bg = t.bg },
        BlinkCmpLabel = { fg = t.fg },
        BlinkCmpLabelDeprecated = { fg = t.keyword, strikethrough = true },
        BlinkCmpLabelMatch = { fg = t.keyword, bold = true },
        BlinkCmpKind = { fg = t.fg },
        BlinkCmpKindFunction = { fg = t.func },
        BlinkCmpKindMethod = { fg = t.func },
        BlinkCmpKindConstructor = { fg = t.func },
        BlinkCmpKindClass = { fg = t.type },
        BlinkCmpKindStruct = { fg = t.type },
        BlinkCmpKindInterface = { fg = t.type },
        BlinkCmpKindTypeParameter = { fg = t.type },
        BlinkCmpKindModule = { fg = t.type },
        BlinkCmpKindNamespace = { fg = t.type },
        BlinkCmpKindVariable = { fg = t.fg },
        BlinkCmpKindProperty = { fg = t.fg },
        BlinkCmpKindField = { fg = t.fg },
        BlinkCmpKindConstant = { fg = t.constant },
        BlinkCmpKindEnum = { fg = t.constant },
        BlinkCmpKindEnumMember = { fg = t.constant },
        BlinkCmpKindKeyword = { fg = t.keyword },
        BlinkCmpKindText = { fg = t.string },
        BlinkCmpKindString = { fg = t.string },
        BlinkCmpKindColor = { fg = t.string },
        BlinkCmpKindSnippet = { fg = t.comment },
        BlinkCmpKindFile = { fg = t.fg },
        BlinkCmpKindFolder = { fg = t.fg },
        BlinkCmpKindReference = { fg = t.fg },
        BlinkCmpKindUnit = { fg = t.fg },
        BlinkCmpKindValue = { fg = t.fg },
        BlinkCmpDocSeparator = { fg = t.fg_dim, bg = t.float_bg },
        BlinkCmpSignatureHelpActiveParameter = { fg = t.keyword, bold = true },
        BlinkCmpGhostText = { fg = t.virtual_text, italic = italic },
        BlinkCmpScrollBarThumb = { bg = t.selection },
        BlinkCmpScrollBarGutter = { bg = t.bg },

        -- lazy.nvim
        LazyButton = { fg = t.fg, bg = t.selection },
        LazyButtonActive = { fg = t.fg, bg = t.float_bg, bold = true },
        LazyH1 = { fg = t.fg, bg = t.selection, bold = true },
        LazyCommit = { fg = t.keyword },
        LazyCommitType = { fg = t.type },
        LazyDir = { fg = t.type },
        LazyNormal = { fg = t.fg, bg = t.bg },
        LazyProgressDone = { fg = t.func },
        LazyProgressTodo = { fg = t.fg_dim },
        LazyReasonCmd = { fg = t.keyword },
        LazyReasonEvent = { fg = t.keyword },
        LazyReasonFt = { fg = t.type },
        LazyReasonImport = { fg = t.func },
        LazyReasonKeys = { fg = t.keyword },
        LazyReasonPlugin = { fg = t.func },
        LazyReasonRuntime = { fg = t.keyword },
        LazyReasonSource = { fg = t.keyword },
        LazyReasonStart = { fg = t.func },
        LazySpecial = { fg = t.func },
        LazyTaskOutput = { fg = t.fg },
        LazyDimmed = { fg = t.fg_dim },
        LazyProp = { fg = t.keyword },

        -- indent-blankline.nvim (ibl)
        IblIndent = { fg = t.selection },
        IblWhitespace = { fg = t.selection },
        IblScope = { fg = t.fg_dim },

        -- mini.nvim
        MiniDiffOverAdd = { bg = t.selection_added },
        MiniDiffOverChange = { bg = t.selection },
        MiniDiffOverContext = { bg = t.float_bg },
        MiniDiffOverDelete = { bg = t.selection_deleted },
        MiniFilesNormal = { fg = t.fg, bg = t.bg },
        MiniFilesBorder = { fg = t.fg, bg = t.bg },
        MiniFilesBorderModified = { fg = t.warn, bg = t.bg },
        MiniFilesTitle = { fg = t.fg, bg = t.bg, bold = true },
        MiniFilesTitleFocused = { fg = t.keyword, bg = t.bg, bold = true },
        MiniFilesDirectory = { fg = t.type, bold = true },
        MiniFilesFile = { fg = t.fg },
        MiniFilesCursorLine = { bg = t.selection },
        MiniPickNormal = { fg = t.fg, bg = t.bg },
        MiniPickBorder = { fg = t.fg, bg = t.bg },
        MiniPickHeader = { fg = t.keyword, bold = true },
        MiniPickMatchCurrent = { fg = t.fg, bg = t.selection },
        MiniPickMatchMarked = { fg = t.func, bg = t.selection },
        MiniPickMatchRanges = { fg = t.keyword, bold = true },
        MiniPickPrompt = { fg = t.keyword, bg = t.bg },
        MiniIconsAzure = { fg = t.func },
        MiniIconsBlue = { fg = t.func },
        MiniIconsCyan = { fg = t.type },
        MiniIconsGreen = { fg = t.added },
        MiniIconsGrey = { fg = t.fg_dim },
        MiniIconsOrange = { fg = t.warn },
        MiniIconsPurple = { fg = t.string },
        MiniIconsRed = { fg = t.error },
        MiniIconsYellow = { fg = t.warn },
        MiniIndentscopeSymbol = { fg = t.fg_dim },
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },

        -- flash.nvim
        FlashBackdrop = { fg = t.fg_dim },
        FlashLabel = { fg = t.fg_inverse, bg = t.warn, bold = true },
        FlashMatch = { fg = t.fg, bg = t.selection },
        FlashCurrent = { fg = t.fg, bg = t.search_current, bold = true },
        FlashPrompt = { fg = t.fg, bg = t.bg },

        -- neo-tree.nvim
        NeoTreeFloatBorder = { fg = t.fg, bg = t.float_bg },
        NeoTreeTitleBar = { fg = t.fg, bg = t.selection, bold = true },
        NeoTreeDirectoryName = { fg = t.type, bold = true },
        NeoTreeDirectoryIcon = { fg = t.type },
        NeoTreeFileName = { fg = t.fg },
        NeoTreeFileIcon = { fg = t.fg },
        NeoTreeFileNameOpened = { fg = t.func },
        NeoTreeRootName = { fg = t.keyword, bold = true },
        NeoTreeIndentMarker = { fg = t.selection },
        NeoTreeExpander = { fg = t.fg_dim },
        NeoTreeCursorLine = { bg = t.selection },
        NeoTreeDimText = { fg = t.fg_dim },
        NeoTreeDotfile = { fg = t.fg_dim },
        NeoTreeModified = { fg = t.warn },
        NeoTreeGitConflict = { fg = t.error, bold = true },
        NeoTreeGitUnstaged = { fg = t.warn },
        NeoTreeGitUntracked = { fg = t.fg_dim },
        NeoTreeTabActive = { fg = t.fg, bg = t.bg, bold = true },
        NeoTreeTabInactive = { fg = t.fg_dim, bg = t.float_bg },
        NeoTreeTabSeparatorActive = { fg = t.bg, bg = t.bg },
        NeoTreeTabSeparatorInactive = { fg = t.float_bg, bg = t.float_bg },
    }
end
