return function(t, config)
    local italic = config.italics or false
    return {
        -- Git commit
        gitcommitSummary = { fg = t.fg, bold = true },
        gitcommitOverflow = { fg = t.error, bold = true },
        gitcommitComment = { fg = t.comment, italic = italic },
        gitcommitHeader = { fg = t.keyword, bold = true },
        gitcommitOnBranch = { fg = t.keyword },
        gitcommitBranch = { fg = t.type, bold = true },
        gitcommitNoBranch = { fg = t.keyword },
        gitcommitUnmerged = { fg = t.error, bold = true },
        gitcommitUntracked = { fg = t.keyword },
        gitcommitDiscarded = { fg = t.error },
        gitcommitSelected = { fg = t.func },
        gitcommitDiscardedType = { fg = t.error },
        gitcommitSelectedType = { fg = t.func },
        gitcommitDiscardedFile = { fg = t.error },
        gitcommitSelectedFile = { fg = t.func },
        gitcommitFile = { fg = t.fg },
        gitcommitTrailerToken = { fg = t.keyword, bold = true },
        gitcommitTrailerValue = { fg = t.string },

        -- Oil.nvim
        OilFile = { fg = t.fg },
        OilDir = { fg = t.type, bold = true },
        OilSymlink = { fg = t.func, italic = italic },
        OilHidden = { fg = t.keyword, italic = italic },
        OilHeader = { fg = t.keyword, bold = true },
        OilBorder = { fg = t.keyword },
        OilWinBar = { fg = t.keyword },
        OilIndent = { fg = t.keyword },
        OilExpander = { fg = t.keyword },
        OilColumns = { fg = t.keyword },
        OilModified = { fg = t.error, bold = true },
        OilDeleted = { fg = t.deleted },
        OilAdded = { fg = t.added },
        OilWarning = { fg = t.warn },
        OilError = { fg = t.error },
        OilSelected = { fg = t.fg, underline = true },
        OilCursorLine = { fg = t.fg, underline = true },
        OilDirectory = { link = "OilDir" },
        OilLink = { link = "OilSymlink" },

        -- nvim-cmp
        CmpItemAbbr = { fg = t.fg },
        CmpItemAbbrDeprecated = { fg = t.keyword, strikethrough = true },
        CmpItemAbbrMatch = { fg = t.keyword, bold = true },
        CmpItemAbbrMatchFuzzy = { fg = t.keyword },
        CmpItemMenu = { fg = t.keyword, italic = italic },
        CmpItemKind = { fg = t.fg },
        CmpItemKindFunction = { fg = t.func },
        CmpItemKindMethod = { fg = t.func },
        CmpItemKindConstructor = { fg = t.func },
        CmpItemKindClass = { fg = t.type },
        CmpItemKindStruct = { fg = t.type },
        CmpItemKindInterface = { fg = t.type },
        CmpItemKindTypeParameter = { fg = t.type },
        CmpItemKindModule = { fg = t.type },
        CmpItemKindNamespace = { fg = t.type },
        CmpItemKindVariable = { fg = t.fg },
        CmpItemKindProperty = { fg = t.fg },
        CmpItemKindField = { fg = t.fg },
        CmpItemKindConstant = { fg = t.constant },
        CmpItemKindEnum = { fg = t.constant },
        CmpItemKindEnumMember = { fg = t.constant },
        CmpItemKindKeyword = { fg = t.keyword },
        CmpItemKindText = { fg = t.string },
        CmpItemKindString = { fg = t.string },
        CmpItemKindColor = { fg = t.string },
        CmpItemKindSnippet = { fg = t.comment },
        CmpItemKindFile = { fg = t.fg },
        CmpItemKindFolder = { fg = t.fg },
        CmpItemKindReference = { fg = t.fg },
        CmpItemKindUnit = { fg = t.fg },
        CmpItemKindValue = { fg = t.fg },

        -- Trouble.nvim
        TroubleNormal = { fg = t.fg, bg = t.bg },
        TroubleNormalNC = { fg = t.fg_dim, bg = t.bg },
        TroubleText = { fg = t.fg, bg = t.bg },
        TroubleIndent = { fg = t.fg, bg = t.bg },
        TroubleCount = { fg = t.fg, bg = t.selection },
        TroublePreview = { fg = t.fg, bg = t.selection },
        TroubleDiagnosticsItemSource = { fg = t.keyword, bg = t.bg, italic = italic },
        TroubleCode = { fg = t.fg_dim, bg = t.bg },
        TroubleIconDirectory = { fg = t.fg_dim, bg = t.bg },
        TroubleIconEvent = { fg = t.fg_dim, bg = t.bg },
        TroubleError = { link = "DiagnosticError" },
        TroubleWarning = { link = "DiagnosticWarn" },
        TroubleInformation = { link = "DiagnosticInfo" },
        TroubleHint = { link = "DiagnosticHint" },

        -- Telescope.nvim
        TelescopeNormal = { fg = t.fg, bg = t.bg },
        TelescopeBorder = { fg = t.fg, bg = t.bg },
        TelescopeTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopeResultsNormal = { fg = t.fg, bg = t.bg },
        TelescopeResultsBorder = { fg = t.fg, bg = t.bg },
        TelescopeResultsTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopeSelection = { fg = t.fg, bg = t.selection },
        TelescopeMultiSelection = { fg = t.func, bg = t.selection },
        TelescopeSelectionCaret = { fg = t.keyword, bg = t.selection },
        TelescopeMatching = { fg = t.keyword, bg = t.bg, bold = true },
        TelescopePromptNormal = { fg = t.fg, bg = t.bg },
        TelescopePromptBorder = { fg = t.fg, bg = t.bg },
        TelescopePromptTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopePromptPrefix = { fg = t.keyword, bg = t.bg },
        TelescopePromptCounter = { fg = t.keyword, bg = t.bg },
        TelescopePreviewNormal = { fg = t.fg, bg = t.bg },
        TelescopePreviewBorder = { fg = t.fg, bg = t.bg },
        TelescopePreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopePreviewLine = { fg = t.fg, bg = t.selection },
        TelescopePreviewMatch = { fg = t.keyword, bg = t.bg, underline = true },
        TelescopeResultsDiffAdd = { fg = t.added, bg = t.bg },
        TelescopeResultsDiffChange = { fg = t.changed, bg = t.bg },
        TelescopeResultsDiffDelete = { fg = t.deleted, bg = t.bg },

        -- fzf-lua
        FzfLuaNormal = { fg = t.fg, bg = t.bg },
        FzfLuaBorder = { fg = t.fg, bg = t.bg },
        FzfLuaTitle = { fg = t.fg, bg = t.bg, bold = true },
        FzfLuaPrompt = { fg = t.keyword, bg = t.bg },
        FzfLuaInfo = { fg = t.keyword, bg = t.bg, italic = italic },
        FzfLuaPath = { fg = t.type, bg = t.bg },
        FzfLuaHeaderBind = { fg = t.keyword, bg = t.bg },
        FzfLuaHeaderText = { fg = t.keyword, bg = t.bg },
        FzfLuaCursor = { fg = t.fg_inverse, bg = t.fg },
        FzfLuaCursorLine = { fg = t.fg, bg = t.selection },
        FzfLuaCursorLineNr = { fg = t.fg_dim, bg = t.selection },
        FzfLuaMatch = { fg = t.keyword, bg = t.bg, bold = true },
        FzfLuaSearch = { fg = t.fg, bg = t.selection },
        FzfLuaMarker = { fg = t.func, bg = t.bg, bold = true },
        FzfLuaPreviewNormal = { fg = t.fg, bg = t.bg },
        FzfLuaPreviewBorder = { fg = t.fg, bg = t.bg },
        FzfLuaPreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        FzfLuaPreviewLine = { fg = t.fg, bg = t.selection },
        FzfLuaPreviewSearch = { fg = t.fg, bg = t.selection },
        FzfLuaPreviewMatch = { fg = t.keyword, bg = t.bg, underline = true },

        -- which-key.nvim
        WhichKey = { fg = t.func, bg = t.bg },
        WhichKeyGroup = { fg = t.type, bg = t.bg, bold = true },
        WhichKeyDesc = { fg = t.fg, bg = t.bg },
        WhichKeySeparator = { fg = t.fg_dim, bg = t.bg },
        WhichKeyFloat = { fg = t.fg, bg = t.bg },
        WhichKeyBorder = { fg = t.fg, bg = t.bg },
        WhichKeyValue = { fg = t.keyword, bg = t.bg },
        WhichKeyNormal = { fg = t.fg, bg = t.bg },
        WhichKeyTitle = { fg = t.fg, bg = t.bg, bold = true },

        -- nvim-notify
        NotifyBackground = { bg = t.fg_inverse },

        -- Snacks.nvim
        SnacksPickerNormal = { fg = t.fg, bg = t.bg },
        SnacksPickerBorder = { fg = t.fg, bg = t.bg },
        SnacksPickerTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerPrompt = { fg = t.keyword, bg = t.bg },
        SnacksPickerInput = { fg = t.fg, bg = t.bg },
        SnacksPickerInputBorder = { fg = t.fg, bg = t.bg },
        SnacksPickerInputTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerList = { fg = t.fg, bg = t.bg },
        SnacksPickerListBorder = { fg = t.fg, bg = t.bg },
        SnacksPickerListTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerListCursorLine = { fg = t.fg, bg = t.selection },
        SnacksPickerPreview = { fg = t.fg, bg = t.bg },
        SnacksPickerPreviewBorder = { fg = t.fg, bg = t.bg },
        SnacksPickerPreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerPreviewLine = { fg = t.fg, bg = t.selection },
        SnacksPickerMatch = { fg = t.keyword, bg = t.bg, bold = true },
        SnacksPickerDir = { fg = t.type, bg = t.bg },
        SnacksPickerFile = { fg = t.fg, bg = t.bg },
        SnacksPickerSelected = { fg = t.func, bg = t.selection },
        SnacksPickerIdx = { fg = t.fg_dim, bg = t.bg },
        SnacksPickerRow = { fg = t.fg_dim, bg = t.bg },
        SnacksPickerCol = { fg = t.fg_dim, bg = t.bg },
        SnacksPickerComment = { fg = t.comment, bg = t.bg, italic = italic },
        SnacksPickerLabel = { fg = t.warn, bg = t.bg, bold = true },

        -- gitsigns.nvim
        GitSignsAdd = { fg = t.added },
        GitSignsChange = { fg = t.changed },
        GitSignsDelete = { fg = t.deleted },
        GitSignsChangedelete = { fg = t.changed },
        GitSignsTopdelete = { fg = t.deleted },
        GitSignsUntracked = { fg = t.fg_dim },
        GitSignsAddNr = { fg = t.added },
        GitSignsChangeNr = { fg = t.changed },
        GitSignsDeleteNr = { fg = t.deleted },
        GitSignsChangedeleteNr = { fg = t.changed },
        GitSignsTopdeleteNr = { fg = t.deleted },
        GitSignsUntrackedNr = { fg = t.fg_dim },
        GitSignsAddLn = { bg = t.selection },
        GitSignsChangeLn = { bg = t.selection },
        GitSignsChangedeleteLn = { bg = t.selection },
        GitSignsUntrackedLn = { bg = t.selection },
        GitSignsAddCul = { fg = t.added },
        GitSignsChangeCul = { fg = t.changed },
        GitSignsDeleteCul = { fg = t.deleted },
        GitSignsChangedeleteCul = { fg = t.changed },
        GitSignsTopdeleteCul = { fg = t.deleted },
        GitSignsUntrackedCul = { fg = t.fg_dim },
        GitSignsAddPreview = { fg = t.added, bg = t.float_bg },
        GitSignsDeletePreview = { fg = t.deleted, bg = t.float_bg },
        GitSignsCurrentLineBlame = { fg = t.virtual_text, italic = italic },
        GitSignsAddInline = { bg = t.selection_added },
        GitSignsDeleteInline = { bg = t.selection_deleted },
        GitSignsChangeInline = { bg = t.selection },
        GitSignsAddLnInline = { bg = t.selection_added },
        GitSignsChangeLnInline = { bg = t.selection },
        GitSignsDeleteLnInline = { bg = t.selection_deleted },
        GitSignsDeleteVirtLn = { fg = t.deleted },
        GitSignsDeleteVirtLnInLine = { fg = t.deleted, bg = t.selection_deleted },
        GitSignsVirtLnum = { fg = t.fg_dim },
        GitSignsStagedAdd = { fg = t.added },
        GitSignsStagedChange = { fg = t.changed },
        GitSignsStagedDelete = { fg = t.deleted },
        GitSignsStagedChangedelete = { fg = t.changed },
        GitSignsStagedTopdelete = { fg = t.deleted },
        GitSignsStagedUntracked = { fg = t.fg_dim },

        -- Noice.nvim
        NoiceCmdline = { fg = t.fg, bg = t.bg },
        NoiceCmdlineIcon = { fg = t.keyword },
        NoiceCmdlineIconSearch = { fg = t.warn },
        NoiceCmdlinePopup = { fg = t.fg, bg = t.bg },
        NoiceCmdlinePopupBorder = { fg = t.fg, bg = t.bg },
        NoiceCmdlinePopupTitle = { fg = t.fg, bg = t.bg, bold = true },
        NoiceConfirm = { fg = t.fg, bg = t.bg },
        NoiceConfirmBorder = { fg = t.fg, bg = t.bg },
        NoiceCursor = { fg = t.fg_inverse, bg = t.fg },
        NoiceFormatConfirm = { fg = t.keyword },
        NoiceFormatConfirmDefault = { fg = t.func, bold = true },
        NoiceFormatDate = { fg = t.keyword, italic = italic },
        NoiceFormatEvent = { fg = t.keyword, italic = italic },
        NoiceFormatKind = { fg = t.keyword },
        NoiceFormatLevelDebug = { fg = t.keyword },
        NoiceFormatLevelError = { fg = t.error },
        NoiceFormatLevelInfo = { fg = t.info },
        NoiceFormatLevelOff = { fg = t.keyword },
        NoiceFormatLevelTrace = { fg = t.keyword },
        NoiceFormatLevelWarn = { fg = t.warn },
        NoiceFormatProgressDone = { fg = t.func, bold = true },
        NoiceFormatProgressTodo = { fg = t.keyword },
        NoiceFormatTitle = { fg = t.fg, bold = true },
        NoiceLspProgressClient = { fg = t.type, bold = true },
        NoiceLspProgressSpinner = { fg = t.keyword },
        NoiceLspProgressTitle = { fg = t.fg },
        NoiceMini = { fg = t.fg, bg = t.bg },
        NoicePopup = { fg = t.fg, bg = t.bg },
        NoicePopupBorder = { fg = t.fg, bg = t.bg },
        NoicePopupmenu = { fg = t.fg, bg = t.bg },
        NoicePopupmenuBorder = { fg = t.fg, bg = t.bg },
        NoicePopupmenuMatch = { fg = t.keyword, bold = true },
        NoicePopupmenuSelected = { fg = t.fg, bg = t.selection },
        NoiceScrollbar = { fg = t.keyword, bg = t.bg },
        NoiceScrollbarThumb = { bg = t.selection },
        NoiceSplit = { fg = t.fg, bg = t.bg },
        NoiceSplitBorder = { fg = t.fg, bg = t.bg },
        NoiceVirtualText = { fg = t.virtual_text, italic = italic },
    }
end
