return function(t, p, config)
    local italic = config.italics or false
    local comment_style = { fg = t.comment, italic = italic }

    return {
        -- Base vim groups
        Comment = comment_style,
        String = { fg = t.string },
        Character = { fg = t.string },
        Number = { fg = t.constant },
        Boolean = { fg = t.constant },
        Float = { fg = t.constant },
        Identifier = { fg = t.variable },
        Function = { fg = t.func },
        Keyword = { fg = t.keyword },
        Statement = { fg = t.keyword },
        Conditional = { fg = t.keyword },
        Repeat = { fg = t.keyword },
        Label = { fg = t.keyword },
        Operator = { fg = t.operator },
        Exception = { fg = t.keyword },
        PreProc = { fg = t.keyword },
        Include = { fg = t.keyword },
        Define = { fg = t.keyword },
        Macro = { fg = t.func },
        PreCondit = { fg = t.keyword },
        Type = { fg = t.type },
        StorageClass = { fg = t.keyword },
        Structure = { fg = t.type },
        Typedef = { fg = t.type },
        Constant = { fg = t.constant },
        SpecialChar = { fg = t.constant },
        Tag = { fg = t.keyword },
        Delimiter = { fg = t.fg },
        SpecialComment = comment_style,
        Debug = { fg = t.warn },

        -- Treesitter comments
        ["@comment"] = comment_style,
        ["@comment.documentation"] = comment_style,
        ["@comment.error"] = { fg = t.error },
        ["@comment.warning"] = { fg = t.warn },
        ["@comment.todo"] = { fg = t.info },
        ["@comment.note"] = { fg = t.hint },

        -- Keywords
        ["@keyword"] = { fg = t.keyword },
        ["@keyword.function"] = { fg = t.keyword },
        ["@keyword.return"] = { fg = t.keyword },
        ["@keyword.modifier"] = { fg = t.keyword },
        ["@keyword.import"] = { fg = t.keyword },
        ["@keyword.export"] = { fg = t.keyword },
        ["@keyword.coroutine"] = { fg = t.keyword },
        ["@keyword.operator"] = { fg = t.keyword },
        ["@keyword.exception"] = { fg = t.keyword },
        ["@keyword.conditional"] = { fg = t.keyword },
        ["@keyword.conditional.ternary"] = { fg = t.keyword },
        ["@keyword.type"] = { fg = t.keyword },
        ["@keyword.repeat"] = { fg = t.keyword },
        ["@keyword.debug"] = { fg = t.keyword },
        ["@keyword.directive"] = { fg = t.keyword },
        ["@keyword.directive.define"] = { fg = t.keyword },
        ["@conditional"] = { fg = t.keyword },
        ["@repeat"] = { fg = t.keyword },
        ["@operator"] = { fg = t.operator },
        ["@label"] = { fg = t.constant },
        ["@storageclass"] = { fg = t.keyword },

        -- Functions
        ["@function"] = { fg = t.func },
        ["@method"] = { fg = t.func },
        ["@function.call"] = { fg = t.func },
        ["@method.call"] = { fg = t.func },
        ["@function.method"] = { fg = t.func },
        ["@function.method.call"] = { fg = t.func },
        ["@constructor"] = { fg = t.type },
        ["@function.builtin"] = { fg = t.func },

        -- Variables
        ["@variable"] = { fg = t.variable },
        ["@variable.parameter"] = { fg = t.variable },
        ["@variable.parameter.builtin"] = { fg = t.variable },
        ["@variable.member"] = { fg = t.variable },
        ["@variable.builtin"] = { fg = t.constant },
        ["@field"] = { fg = t.variable },
        ["@property"] = { fg = t.variable },

        -- Types
        ["@type"] = { fg = t.type },
        ["@type.builtin"] = { fg = t.type },
        ["@type.qualifier"] = { fg = t.keyword },
        ["@type.definition"] = { fg = t.type },
        ["@namespace"] = { fg = t.type },

        -- Modules
        ["@namespace.import"] = { fg = t.variable },
        ["@module"] = { fg = t.variable },
        ["@module.builtin"] = { fg = t.variable },

        -- Strings
        ["@string"] = { fg = t.string },
        ["@string.special"] = { fg = t.string },
        ["@string.documentation"] = comment_style,
        ["@string.regexp"] = { fg = t.string },
        ["@string.escape"] = { fg = t.keyword },
        ["@string.special.symbol"] = { fg = t.keyword },
        ["@string.special.url"] = { fg = t.func, underline = true },
        ["@string.special.path"] = { fg = t.string },
        ["@character"] = { fg = t.string },
        ["@character.special"] = { fg = t.keyword },

        -- Constants
        ["@boolean"] = { fg = t.constant },
        ["@number"] = { fg = t.constant },
        ["@number.float"] = { fg = t.constant },
        ["@constant"] = { fg = t.constant },
        ["@constant.builtin"] = { fg = t.constant },
        ["@symbol"] = { fg = t.constant },

        -- Punctuation
        ["@punctuation"] = { fg = t.fg },
        ["@punctuation.bracket"] = { fg = t.fg },
        ["@punctuation.delimiter"] = { fg = t.fg },
        ["@punctuation.special"] = { fg = t.fg },

        -- Tags (JSX/HTML)
        ["@tag"] = { fg = t.keyword },
        ["@tag.attribute"] = { fg = t.variable },
        ["@tag.delimiter"] = { fg = t.fg },
        ["@tag.builtin"] = { fg = t.fg },

        -- Attributes and macros
        ["@attribute"] = { fg = t.keyword },
        ["@attribute.builtin"] = { fg = t.keyword },
        ["@constant.macro"] = { fg = t.constant },
        ["@function.macro"] = { fg = t.func },

        -- Markup
        ["@markup.strong"] = { bold = true },
        ["@markup.italic"] = { italic = true },
        ["@markup.strikethrough"] = { strikethrough = true },
        ["@markup.underline"] = { underline = true },
        ["@markup.heading"] = { fg = t.keyword, bold = true },
        ["@markup.quote"] = { fg = t.comment, italic = true },
        ["@markup.math"] = { fg = t.constant },
        ["@markup.link"] = { fg = t.func, underline = true },
        ["@markup.link.label"] = { fg = t.func },
        ["@markup.link.url"] = { fg = t.func, underline = true },
        ["@markup.raw"] = { fg = t.string },
        ["@markup.raw.block"] = { fg = t.string },
        ["@markup.list"] = { fg = t.fg },
        ["@markup.list.checked"] = { fg = t.added },
        ["@markup.list.unchecked"] = { fg = t.error },

        -- Diff
        ["@diff.plus"] = { link = "DiffAdd" },
        ["@diff.minus"] = { link = "DiffDelete" },
        ["@diff.delta"] = { link = "DiffChange" },

        -- LSP semantic tokens
        ["@lsp.type.variable"] = { link = "@variable" },
        ["@lsp.type.parameter"] = { link = "@variable.parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.field"] = { link = "@field" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.method"] = { link = "@method.call" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.interface"] = { link = "@type" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.typeParameter"] = { link = "@type" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.keyword"] = { link = "@keyword" },
        ["@lsp.type.operator"] = { link = "@operator" },
        ["@lsp.type.string"] = { link = "@string" },
        ["@lsp.type.number"] = { link = "@number" },
        ["@lsp.type.boolean"] = { link = "@boolean" },
        ["@lsp.type.comment"] = {},
        ["@lsp.type.lifetime"] = { link = "@label" },
        ["@lsp.type.modifier"] = { link = "@keyword.modifier" },
        ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
        ["@lsp.typemod.variable.readonly"] = { link = "@constant" },
        ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
        ["@lsp.typemod.namespace.attribute"] = { link = "@attribute" },
        ["@lsp.typemod.interface.declaration"] = { link = "@type" },
        ["@lsp.typemod.struct.declaration"] = { link = "@type" },
        ["@lsp.typemod.enum.declaration"] = { link = "@type" },
        ["@lsp.typemod.type.declaration"] = { link = "@type" },
        ["@lsp.typemod.class.declaration"] = { link = "@type" },
        ["@lsp.typemod.class.globalScope"] = { link = "@type" },
        ["@lsp.typemod.generic.attribute"] = { link = "@attribute" },
        LspInlayHint = { fg = t.comment, italic = true },
    }
end
